channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=23.3.2
- pip:
  - mlflow==2.8.0
  - cffi==1.16.0
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - lightgbm==4.1.0
  - matplotlib==3.8.0
  - numpy==1.24.1
  - packaging==23.2
  - pandas==2.1.2
  - psutil==5.9.6
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.9.3
name: mlflow-env
